### ISSUE TITLE
Investigate Raspberry Pi

### ISSUE THREAD

**Issue by DevanTurtle7** [talos-rit/camera_arm#4]
Investigate the usage of Raspberry Pi 4. Is the hardware sufficient enough or do we need more power?

**Comment by nolanporter77** [comment]
Adding more context to this research task:

Setting up raspberry pi to work on RIT wifi network and allow us to ssh into it.
Proving the raspberry pi can work in tandem with our webcam.
Proving this setup will be effective for our algorithm to track the speaker.
